# --
# Copyright (C) 2019-2024 Rother OSS GmbH, https://otobo.de/
# --
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU AFFERO General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
# or see http://www.gnu.org/licenses/agpl.txt.
# --

# Valid log levels are:
# debug, info, notice, warning, error, critical, alert, emergency
# critical, alert and emergency are not currently used.
#
# Please use boolean values in this config file. Negated options (--no-*) are
# not permitted here. Explicitly set options to true or false.
#
# Some of these values deviate from the regular perlimports defaults. In
# particular, you're encouraged to leave preserve_duplicates and
# preserve_unused disabled.

# Call with a command like:
#   perlimports --lint  Kernel/Autoload Kernel/Language Kernel/Modules Kernel/System Kernel/Config Kernel/GenericInterface Kernel/Output scripts bin 2>&1 | tee perlimports.out

cache                           = false # setting this to true is currently discouraged
ignore_modules                  = [
    "Test2::V0",
    "Try::Tiny",
    "Kernel::System::VariableCheck",
    "Kernel::System::UnitTest::RegisterOM",
    "Kernel::System::UnitTest::RegisterDriver",
    "Kernel::System::UnitTest::Selenium"
]
ignore_modules_filename         = ""
ignore_modules_pattern          = "" # regex like "^(Foo|Foo::Bar)"
ignore_modules_pattern_filename = ""
libs                            = [".", "Kernel/cpan-lib"]
log_filename                    = ""
log_level                       = "warn"
never_export_modules            = []
never_export_modules_filename   = ""
padding                         = false
preserve_duplicates             = false
preserve_unused                 = false
tidy_whitespace                 = false
