# --
# OTOBO is a web-based ticketing system for service organisations.
# --
# Copyright (C) 2001-2020 OTRS AG, https://otrs.com/
# Copyright (C) 2019-2026 Rother OSS GmbH, https://otobo.io/
# --
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# --

use v5.24;
use strict;
use warnings;
use utf8;

# core modules

# CPAN modules
use Test2::V0;
use Test2::Tools::Explain;
use File::Path       qw(make_path rmtree);
use Path::Class      qw(file);
use Cpanel::JSON::XS qw(decode_json);

# OTOBO modules
use Kernel::System::UnitTest::RegisterOM;    # Set up $Kernel::OM
use Kernel::System::VariableCheck qw(:all);
use Test2::Require::OTOBO::OpenSSL;          # run test script only when the openssl binary is available

# NOTE: This test relies on the following SMIME certs in $HOME/scripts/test/sample/SMIME
# - SMIMECertificate-1.asc
# - SMIMEPrivateKey-1.asc
# - SMIMECertificate-2.asc
# - SMIMEPrivateKey-2.asc
# - SMIMECertificate-3.asc
# - SMIMEPrivateKey-3.asc
# These certs are valid for a year.
# The certs can be regenerated by running 'perl scripts/test/sample/SMIME/make_certs.pl'
# from /opt/otobo. This will also regenerated the scripts/test/sample/SMIME/smime_test.json
# file containing the variable text expectations.

# get needed objects
my $ConfigObject = $Kernel::OM->Get('Kernel::Config');
my $DBObject     = $Kernel::OM->Get('Kernel::System::DB');
my $MainObject   = $Kernel::OM->Get('Kernel::System::Main');

# get helper object
$Kernel::OM->ObjectParamAdd(
    'Kernel::System::UnitTest::Helper' => {
        RestoreDatabase => 1,
    },
);
my $Helper = $Kernel::OM->Get('Kernel::System::UnitTest::Helper');

# get configuration
my $Home = $ConfigObject->Get('Home');

# set up temporary dirs
my $Random      = $Helper->GetRandomID;
my $CertPath    = "$Home/var/tmp/certs_$Random";
my $PrivatePath = "$Home/var/tmp/private_$Random";
$CertPath    =~ s{/{2,}}{/}smxg;
$PrivatePath =~ s{/{2,}}{/}smxg;
rmtree($CertPath);
rmtree($PrivatePath);
make_path( $CertPath,    { chmod => 0770 } );    ## no critic qw(ValuesAndExpressions::ProhibitLeadingZeros)
make_path( $PrivatePath, { chmod => 0770 } );    ## no critic qw(ValuesAndExpressions::ProhibitLeadingZeros)
$ConfigObject->Set(
    Key   => 'SMIME::CertPath',
    Value => $CertPath
);
$ConfigObject->Set(
    Key   => 'SMIME::PrivatePath',
    Value => $PrivatePath
);

my $OpenSSLBin = $ConfigObject->Get('SMIME::Bin') || '/usr/bin/openssl';

# get the openssl major version, e.g. 1 for version 1.0.0
# openssl 0.9 is no longer considered for this test script, as openssl 1.0.0 was already released in 2010
my $OpenSSLVersionString = qx{$OpenSSLBin version};    # e.g. "OpenSSL 1.1.1f  31 Mar 2020"
diag "OpenSSL $OpenSSLVersionString";
my ($OpenSSLMajorVersion) = $OpenSSLVersionString =~ m{ \A (?: (?: Open|Libre)SSL )? \s* ( \d )  }xmsi;
ok( $OpenSSLMajorVersion >= 0, 'openssl has version 1.0.0 or newer' );

# set config
$ConfigObject->Set(
    Key   => 'SMIME',
    Value => 1,
);

# create crypt object
my $SMIMEObject = $Kernel::OM->Get('Kernel::System::Crypt::SMIME');

if ($SMIMEObject) {
    pass('got SMIME support');
}
else {
    diag "NOTICE: No SMIME support!";

    if ( !-e $OpenSSLBin ) {
        fail("$OpenSSLBin exists");
    }
    elsif ( !-x $OpenSSLBin ) {
        fail("$OpenSSLBin is executable!");
    }
    elsif ( !-e $CertPath ) {
        fail("$CertPath exists");
    }
    elsif ( !-d $CertPath ) {
        fail("$CertPath is a directory");
    }
    elsif ( !-r $CertPath ) {
        fail("$CertPath is readable");
    }
    elsif ( !-e $PrivatePath ) {
        fail("$PrivatePath exists");
    }
    elsif ( !-d $PrivatePath ) {
        fail("$PrivatePath is a directory");
    }
    elsif ( !-w $PrivatePath ) {
        fail("$PrivatePath is writable");
    }

    done_testing;

    exit 0;
}

my $TestConfigJSON = file("$Home/scripts/test/sample/SMIME/smime_test.json")->slurp;
my $TestConfig     = decode_json($TestConfigJSON);

my %Search = (
    1 => 'unittest@example.org',
    2 => 'unittest2@example.org',
    3 => 'unittest3@example.org',
);

my $TestText = 'hello1234567890öäüß';

# Test the three test cases that are set up in the JSON file
# These test were originally in SMIME.t
my ( %Count2Filename, %Count2Crypted );
for my $Count ( 1 .. 3 ) {
    subtest "Testcase $Count" => sub {

        my @CertsBeforeAdd = $SMIMEObject->Search( Search => $Search{$Count} );
        is( \@CertsBeforeAdd, [], 'Search() before CertificateAdd() has no results' );

        # add certificate ...
        my $CertString = $MainObject->FileRead(
            Directory => $ConfigObject->Get('Home') . '/scripts/test/sample/SMIME/',
            Filename  => "SMIMECertificate-$Count.asc",
        );
        my %Result = $SMIMEObject->CertificateAdd( Certificate => $CertString->$* );
        ok( $Result{Successful}, "CertificateAdd() - $Result{Message}" );

        # test if the added certificate from file is the same as in unittest file
        is(
            $CertString->$*,
            $TestConfig->{$Count}->{Pem},
            "CertificateSearch() - Test if added cert from file is the same as in unittest file",
        );

        # Search after the certificate has been added.
        my @Certs = $SMIMEObject->CertificateSearch(
            Search => $Search{$Count},
        );
        like( \@Certs, array { item hash { filename => T() }; end() }, "single result CertificateSearch()" );
        $Count2Filename{$Count} = $Certs[0]->{Filename};

        IDTEST:
        for my $ID ( sort keys $TestConfig->{$Count}->%* ) {

            next IDTEST if $ID eq 'Pem';

            if ( IsArrayRefWithData( $TestConfig->{$Count}->{$ID} ) ) {

                my $Success = 0;

                for my $String ( @{ $TestConfig->{$Count}->{$ID} } ) {
                    $Success = 1 if $Certs[0]->{$ID} eq $String;
                }

                if ( !$Success ) {
                    diag "$ID not found in list: '$Certs[0]->{$ID}'";
                }

                ok( $Success, "CertificateSearch() - $ID" );
            }
            else {
                is(
                    $Certs[0]->{$ID} || '',
                    $TestConfig->{$Count}->{$ID},
                    "CertificateSearch() - $ID",
                );
            }
        }

        # and private key
        my $KeyString = $MainObject->FileRead(
            Directory => $ConfigObject->Get('Home') . "/scripts/test/sample/SMIME/",
            Filename  => "SMIMEPrivateKey-$Count.asc",
        );
        my $Secret = $MainObject->FileRead(
            Directory => $ConfigObject->Get('Home') . "/scripts/test/sample/SMIME/",
            Filename  => "SMIMEPrivateKeyPass-$Count.asc",
        );
        %Result = $SMIMEObject->PrivateAdd(
            Private => ${$KeyString},
            Secret  => ${$Secret},
        );
        ok( $Result{Successful}, "PrivateAdd()" );

        my @Keys = $SMIMEObject->PrivateSearch( Search => $Search{$Count} );

        ok( $Keys[0], "PrivateSearch()" );

        my $CertificateString = $SMIMEObject->CertificateGet(
            Hash        => $Certs[0]->{Hash},
            Fingerprint => $Certs[0]->{Fingerprint},
        );
        ok( $CertificateString, "CertificateGet()" );

        my $PrivateKeyString = $SMIMEObject->PrivateGet(
            Hash    => $Keys[0]->{Hash},
            Modulus => $Certs[0]->{Modulus},
        );
        ok( $PrivateKeyString, "PrivateGet()" );

        # crypt
        my $Crypted = $SMIMEObject->Crypt(
            Message  => $TestText,
            Filename => $Certs[0]->{Filename},
        );
        $Count2Crypted{$Count} = $Crypted;
        ok( $Crypted, "Crypt() by cert filename" );

        ok(
            $Crypted =~ m{Content-Type: application/(x-)?pkcs7-mime;}
                && $Crypted =~ m{Content-Transfer-Encoding: base64},
            "Crypt() - Data seems ok (crypted)",
        );

        # decrypt with the correct certificate
        {
            my %Decrypt = $SMIMEObject->Decrypt(
                Message  => $Crypted,
                Filename => $Certs[0]->{Filename},
            );
            ok( $Decrypt{Successful}, "Decrypt() by cert filename - Successful: $Decrypt{Message}" );
            is( $Decrypt{Data}, $TestText, "Decrypt() - Data" );
        }

        # sign
        my $Sign = $SMIMEObject->Sign(
            Message  => $TestText,
            Filename => $Certs[0]->{Filename},
        );

        ok( $Sign, "Sign()" );

        # verify
        my %Verify = $SMIMEObject->Verify(
            Message => $Sign,
            CACert  => "$CertPath/$Certs[0]->{Filename}",
        );

        ok( $Verify{Successful}, "Verify() - self signed sending certificate path" );
        is( $Verify{SignerCertificate}, $TestConfig->{$Count}->{Pem}, "Verify()" );

        # verify failure on manipulated text
        my $ManipulatedSign = $Sign;
        $ManipulatedSign =~ s{Q}{W}g;
        %Verify = $SMIMEObject->Verify(
            Message => $ManipulatedSign,
            CACert  => "$CertPath/$Certs[0]->{Filename}",
        );

        ok( !$Verify{Successful}, "Verify() - on manipulated text" );

        # file checks
        # TODO: signing binary files doesn't seem to work at all, maybe because they need to be converted
        #       to base64 first?
        #    for my $File (qw(xls txt doc png pdf))
        for my $File (qw(txt)) {
            subtest "Fileextension $File" => sub {
                my $Content = $MainObject->FileRead(
                    Directory => $ConfigObject->Get('Home') . "/scripts/test/sample/SMIME/",
                    Filename  => "PGP-Test1.$File",
                    Mode      => 'binmode',
                );
                my $Reference = ${$Content};
                $Reference =~ s{\n}{\r\n}gsm;

                # crypt
                my $Crypted = $SMIMEObject->Crypt(
                    Message     => $Reference,
                    Hash        => $Certs[0]->{Hash},
                    Fingerprint => $Certs[0]->{Fingerprint},
                );
                ok( $Crypted, "Crypt()" );
                ok(
                    $Crypted =~ m{Content-Type: application/(x-)?pkcs7-mime;}
                        && $Crypted =~ m{Content-Transfer-Encoding: base64},
                    "Crypt() - Data seems ok (crypted)",
                );

                # decrypt
                my %Decrypt = $SMIMEObject->Decrypt(
                    Message     => $Crypted,
                    Hash        => $Certs[0]->{Hash},
                    Fingerprint => $Certs[0]->{Fingerprint},
                );
                ok( $Decrypt{Successful}, "Decrypt() - Successful .$File" );
                is( $Decrypt{Data}, $Reference, "Decrypt() - Data .$File" );

                # sign
                my $Signed = $SMIMEObject->Sign(
                    Message     => $Reference,
                    Hash        => $Keys[0]->{Hash},
                    Fingerprint => $Keys[0]->{Fingerprint},
                );

                ok( $Signed, "Sign() .$File" );

                # verify
                my %Verify = $SMIMEObject->Verify(
                    Message => $Signed,
                    CACert  => "$CertPath/$Certs[0]->{Filename}",
                );
                ok( $Verify{Successful}, "Verify() .$File" );
                is(
                    $Verify{SignerCertificate},
                    $TestConfig->{$Count}->{Pem},
                    "Verify() .$File - SignerCertificate",
                );
            }
        }
    };
}

# decrypt with the incorrect certificate
for my $Count ( 1 .. 3 ) {
    my $InvalidCertCount = ( $Count % 3 ) + 1;      # 3 => 1
    my %Decrypt          = $SMIMEObject->Decrypt(
        Message            => $Count2Crypted{$Count},
        SearchingNeededKey => 1,
        Filename           => $Count2Filename{$InvalidCertCount},
    );
    diag explain( \%Decrypt );
    ok( !$Decrypt{Successful}, "Error decrypting by cert filename" );
    is(
        $Decrypt{Message},
        'Impossible to decrypt with installed private keys!',
        'Message for failed decrypt'
    );
}

# delete keys
for my $Count ( 1 .. 3 ) {
    subtest "delete keys $Count" => sub {
        my @Keys = $SMIMEObject->Search(
            Search => $Search{$Count},
        );
        ok( $Keys[0], "Search()" );
        my %Result = $SMIMEObject->PrivateRemove(
            Hash    => $Keys[0]->{Hash},
            Modulus => $Keys[0]->{Modulus},
        );
        ok( $Result{Successful}, "PrivateRemove() - $Result{Message}" );

        %Result = $SMIMEObject->CertificateRemove(
            Hash        => $Keys[0]->{Hash},
            Fingerprint => $Keys[0]->{Fingerprint},
        );

        ok( $Result{Successful}, "CertificateRemove()" );

        @Keys = $SMIMEObject->Search( Search => $Search{$Count} );
        ok( !$Keys[0], "Search()" );
    };
}

rmtree($CertPath);
rmtree($PrivatePath);

done_testing;
