# --
# OTOBO is a web-based ticketing system for service organisations.
# --
# Copyright (C) 2001-2020 OTRS AG, https://otrs.com/
# Copyright (C) 2019-2025 Rother OSS GmbH, https://otobo.io/
# --
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# --

package Kernel::System::Web::InterfaceMigrateFromOTRS;

use v5.24;
use strict;
use warnings;
use namespace::autoclean;
use utf8;

use parent qw(Plack::Component);

# core modules

# CPAN modules

# OTOBO modules
use Kernel::Language             qw(Translatable);
use Kernel::Output::HTML::Layout ();

our @ObjectDependencies = (
    'Kernel::Config',
    'Kernel::Output::HTML::Layout',
    'Kernel::System::Log',
    'Kernel::System::Main',
    'Kernel::System::Web::Request',
    'Kernel::System::Web::Response',
);

=head1 NAME

Kernel::System::Web::InterfaceMigrateFromOTRS - the migration web interface

=head1 SYNOPSIS

    # This module constitutes a Plack component that is meant to implement a Plack app.
    # See bin/psgi-bin/otobo.psgi on how to use it.

=head1 DESCRIPTION

This module generates the HTTP response for F<migration.pl>.
It is meant to be used within a Plack request handler.
See F<bin/psgi-bin/otobo.psgi> for the real live usage.

=head1 PRIVATE FUNCTIONS

=head2 _Content()

Generate content.
Set headers in Kernels::System::Web::Request singleton as side effect.
Can die and throw a C<Kernel::System::Web::Exception> exception. That exception
is expected to be caught by the middleware C<Plack::Middleware::HTTPExceptions>.

    my $Content = _Content();

or with debugging:

    my $Content = _Content( Debug => 1 );

=cut

sub _Content {
    my (%IncomingParam) = @_;

    my $Debug = $IncomingParam{Debug} || 0;

    # Collect object parameters for the Layout object
    my %Param;
    {
        my $ParamObject = $Kernel::OM->Get('Kernel::System::Web::Request');

        $Param{Action}     = $ParamObject->GetParam( Param => 'Action' )     || 'MigrateFromOTRS';
        $Param{Subaction}  = $ParamObject->GetParam( Param => 'Subaction' )  || '';
        $Param{NextScreen} = $ParamObject->GetParam( Param => 'NextScreen' ) || '';
    }

    $Kernel::OM->ObjectParamAdd(
        'Kernel::Output::HTML::Layout' => {
            %Param,
        },
    );

    my $LayoutObject = $Kernel::OM->Get('Kernel::Output::HTML::Layout');

    # check secure mode
    if ( $Kernel::OM->Get('Kernel::Config')->Get('SecureMode') ) {
        return join '',
            $LayoutObject->Header(),
            $LayoutObject->Error(
                Message => Translatable('SecureMode active!'),
                Comment => Translatable(
                    'If you want to re-run migration.pl, then disable the SecureMode in the SysConfig.'
                ),
            ),
            $LayoutObject->Footer();
    }

    # run modules if a version value exists
    if ( $Kernel::OM->Get('Kernel::System::Main')->Require("Kernel::Modules::$Param{Action}") ) {

        # create $GenericObject
        my $GenericObject = ( 'Kernel::Modules::' . $Param{Action} )->new(
            %Param,
            Debug => $Debug,
        );

        # output filters are not applied for this interface
        return $GenericObject->Run();
    }

    # return an error screen as the fallback
    return join '',
        $LayoutObject->Header(),
        $LayoutObject->Error(
            Message => $LayoutObject->{LanguageObject}->Translate( 'Action "%s" not found!', $Param{Action} ),
            Comment => Translatable('Please contact the administrator.'),
        ),
        $LayoutObject->Footer();
}

=head1 PUBLIC INTERFACE

=head2 call()

Generate a PSGI Response object from the content generated by C<_Content()>.
This is the subroutine that is called in F<otobo.psgi>.

    my $Response = $Interface->call();

=cut

sub call {
    my ( $Self, $Env ) = @_;

    my $Debug = $Self->{Debug} || 0;

    # The OTOBO modules which generate the content get their input
    # from the Kernel::System::Web::Request singleton, that is the ParamObject.
    # Make the PSGI environment available to the constructor of the ParamObject.
    $Kernel::OM->ObjectParamAdd(
        'Kernel::System::Web::Request' => {
            PSGIEnv => $Env,
        },
    );

    # register object params for Kernel::System::Log
    # as the PerformanceLog middleware is not used yet for this interface
    $Kernel::OM->ObjectParamAdd(
        'Kernel::System::Log' => {
            LogPrefix => $Kernel::OM->Get('Kernel::Config')->Get('CGILogPrefix') || 'Installer',
        },
    );

    # debug info
    if ($Debug) {
        my $Interface = __PACKAGE__ =~ s/.*::(\w+)$/$1/r;

        $Kernel::OM->Get('Kernel::System::Log')->Log(
            Priority => 'debug',
            Message  => "Global handle for $Interface started...",
        );
    }

    # Note that the layout object mustn't be created before calling _Content().
    # This is because _Content() might want to set object params before the initial creations.
    # A notable example is the SetCookies parameter.
    my $Content = _Content( Debug => $Debug );

    # no output filters in InterfaceMigrateFromOTRS.

    # The HTTP headers of the OTOBO web response object already have been set up.
    # Enhance it with the HTTP status code and the content.
    return $Kernel::OM->Get('Kernel::System::Web::Response')->Finalize(
        Content => $Content,
    );
}

1;
