#!/bin/sh

# Override the build command for automated builds on Docker Hub.
# See https://docs.docker.com/docker-hub/builds/advanced/ for the list of preset environment variables.
echo docker build\
 --build-arg "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"\
 --build-arg "DOCKER_TAG=$DOCKER_TAG"\
 --build-arg "GIT_COMMIT=$SOURCE_COMMIT"\
 --build-arg "GIT_BRANCH=$SOURCE_BRANCH"\
 --build-arg "GIT_REPO=$(git config --get remote.origin.url)"\
 -f $DOCKERFILE_PATH\
 -t $IMAGE_NAME\
 .
