#!/bin/bash

# Set additional Docker image tags for automated build on Docker hub

# DOCKER_REPO checks whether this script is called by an automated Docker Hub build.
echo "hi from pull_post"
set -o nounset
: "$DOCKER_REPO"
: "$DOCKER_TAG"
: "$IMAGE_NAME"

# Check whether this is a build for a OTOBO release.
echo "tag before: -->$DOCKER_TAG<--"
[[ $DOCKER_TAG =~ ^tag-289-post_push-[0-9].* ]] || exit 0
echo "tag after: -->$DOCKER_TAG<--"

# assign the additional label 'latest'
local tag=latest-test-289
echo "cmd : -->docker tag $IMAGE_NAME ${DOCKER_REPO}:${tag}<--"
docker tag $IMAGE_NAME ${DOCKER_REPO}:${tag}
echo "cmd : -->docker push ${DOCKER_REPO}:${tag}<--"
docker push ${DOCKER_REPO}:${tag}

# See also https://docs.docker.com/docker-hub/builds/
# See also https://docs.docker.com/docker-hub/builds/advanced/
# See also https://windsock.io/automated-docker-image-builds-with-multiple-tags/
# See also https://github.com/RotherOSS/otobo/issues/289
