#!/bin/bash

# Set additional Docker image tags for automated build on Docker hub

# DOCKER_REPO checks whether this script is called by an automated Docker Hub build.
set -o nounset
: "$DOCKER_REPO"
: "$DOCKER_TAG"
: "$IMAGE_NAME"

# Check whether this is a build for a OTOBO release.
[[ $DOCKER_TAG =~ ^rel\-[0-9].* ]] || exit 0

# assign the additional label 'latest'
tag=latest
echo "adding the tag '$tag' to the image $IMAGE_NAME"
docker tag $IMAGE_NAME ${DOCKER_REPO}:${tag}
docker push ${DOCKER_REPO}:${tag}

# See also https://docs.docker.com/docker-hub/builds/
# See also https://docs.docker.com/docker-hub/builds/advanced/
# See also https://windsock.io/automated-docker-image-builds-with-multiple-tags/
# See also https://github.com/RotherOSS/otobo/issues/289
