%YAML 1.1
---

# This is a local composite action for building Docker images and pushing them to Docker Hub.
# This action is ntended to be used by the workflows docker_image_builder_rel.yml and
# docker_image_builder_devel.yml.
name: 'DockerImageBuilder'

description: 'Composite action for building Docker images and pushing them to Docker Hub'

inputs:
  fix_cldr:
    description: |
      Whether the CLDR workaround is needed
    required: false
    default: 0

  dockerfile:
    description: |
      Name of the Dockerfile for building the Docker image.
    required: true

  context:
    description: |
      Relative path in the sandbox which serves as the context for building the Docker image.
    required: true

  target:
    description: |
      Target in the Dockerfile which will be built.
    required: true

  dockerhub_tags:
    description: |
      List of tags under which the new Docker image should be available on Docker hub.
    required: true

#outputs:

runs:

  using: 'composite'

  steps:

      -
        # Print some info that is useful for development and verification.
        # Use environment variables as the generated JSON may contain
        # unescapted quotes which mess up bash syntax.
        name: 'print devel output as JSON'
        shell: bash
        run: |
          echo 'env: '    $ENV_AS_JSON
          echo 'github: ' $GITHUB_AS_JSON
        env:
          ENV_AS_JSON:    ${{ toJSON(env) }}
          GITHUB_AS_JSON: ${{ toJSON(github) }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        # a workaround for a build failure for the 11.0.7 release
        # see https://github.com/RotherOSS/otobo/issues/4103
        # can't use github.sha here as we need the commit of the checked out branch
        name: 'use Locale::CLDR 0.46.1 for building OTOBO 11.0.7'
        if: ${{ inputs.target == 'otobo-web' && inputs.fix_cldr }}
        shell: bash
        run: |
          sed -i.bak -e 's/0.44.1/0.46.0/' cpanfile.docker

      -
        # Build the image but do not push it to Docker Hub yet.
        # Enable caching with Github Actions Cache, which is limited to 10 GB.
        # context: .  indicates that the top level ot the current checkout is used as the build context.
        name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          pull: true
          build-args: |
            BUILD_DATE=${{ env.otobo_build_date }}
            DOCKER_TAG=${{ env.otobo_docker_tag }}
            GIT_REPO=${{ github.repositoryUrl }}
            GIT_BRANCH=${{ env.otobo_branch }}
            GIT_COMMIT=${{ env.otobo_commit }}
          target: ${{ inputs.target }}
          tags: ${{ env.otobo_ref }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      -
        # Show some files in the image just to check sanity.
        # otobo_first_time hasn't run yet, so /opt/otobo is still empty
        name: Info
        if: inputs.target == 'otobo-web'
        shell: bash
        run: |
          docker run --rm -w /opt/otobo_install/otobo_next --entrypoint /bin/bash $otobo_ref -c "more git-repo.txt git-branch.txt git-commit.txt RELEASE | cat"

      -
        # finally upload to DockerHub
        # using the provided dockerhub_tags
        # the built image is already available in the job
        name: Push to DockerHub
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          pull: true
          build-args: |
            BUILD_DATE=${{ env.otobo_build_date }}
            DOCKER_TAG=${{ env.otobo_docker_tag }}
            GIT_REPO=${{ github.repositoryUrl }}
            GIT_BRANCH=${{ env.otobo_branch }}
            GIT_COMMIT=${{ env.otobo_commit }}
          target: ${{ inputs.target }}
          tags: ${{ inputs.dockerhub_tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
