# Config for nginx serving as a reverse proxy for the OTOBO web application.

# This config is based on default.conf in the nginx installation

# The master process runs as root.
# When no user is configured then the workers will run as nobody.
#user

proxy_send_timeout 120;
proxy_read_timeout 99999;
proxy_buffering    off;
#tcp_nodelay        on; Already configured in /etc/nginx/nginx.conf

# Do not serve HTTP, but redirect to HTTPS instead.
# See https://linuxize.com/post/redirect-http-to-https-in-nginx/.
server {
    listen 80;
    listen [::]:80;

    server_name  localhost;

    # allow large uploads of files
    client_max_body_size 1G;

    #access_log  /var/log/nginx/host.access.log  main;

    # proxy to the otobo webapp accessible from the host
    # pass on information about the client
    location / {
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass       http://localhost:5000/;
    }
}
