%YAML 1.1
---
name: 'DockerImageUpdateAll'

# This workflow has been adapted from the workflow
# https://github.com/marketplace/actions/docker-image-update-checker#minimal

# This workflow checks whether there are updated base images and
# creates release images on Docker Hub.
# For each supported releas branch only the last three patch level releases are checked.
# Note that the list of release tags must be updated when there are new patch level releases.

on:

  # The trigger on 'workflow_dispatch' allows to start the workflow manually
  # via https://github.com/RotherOSS/otobo/actions/workflows/docker_image_update_all.yml
  workflow_dispatch:

  # Currenty there is no automatically scheduled rebuild.
  #schedule:
  #  - cron: '37 2 * * *'
jobs:
  CheckDockerImageUpdate:
    runs-on: 'ubuntu-latest'

    # This long list is a workaround so that
    # the outputs from all matrix iterations can be collected.
    outputs:

      otobo_web_rel_10_0_23: ${{ steps.collect_summary.outputs.otobo_web_rel_10_0_23 }}
      otobo_web_rel_10_0_24: ${{ steps.collect_summary.outputs.otobo_web_rel_10_0_24 }}
      otobo_web_rel_10_0_25: ${{ steps.collect_summary.outputs.otobo_web_rel_10_0_25 }}
      otobo_web_latest_10_0: ${{ steps.collect_summary.outputs.otobo_web_latest_10_0 }}

      otobo_web_rel_10_1_12: ${{ steps.collect_summary.outputs.otobo_web_rel_10_1_12 }}
      otobo_web_rel_10_1_13: ${{ steps.collect_summary.outputs.otobo_web_rel_10_1_13 }}
      otobo_web_rel_10_1_14: ${{ steps.collect_summary.outputs.otobo_web_rel_10_1_14 }}
      otobo_web_latest_10_1: ${{ steps.collect_summary.outputs.otobo_web_latest_10_1 }}

      otobo_web_rel_11_0_8: ${{ steps.collect_summary.outputs.otobo_web_rel_11_0_8 }}
      otobo_web_rel_11_0_9: ${{ steps.collect_summary.outputs.otobo_web_rel_11_0_9 }}
      otobo_web_rel_11_0_10: ${{ steps.collect_summary.outputs.otobo_web_rel_11_0_10 }}
      otobo_web_latest_11_0: ${{ steps.collect_summary.outputs.otobo_web_latest_11_0 }}

      #otobo_elasticsearch_rel_10_0_23: ${{ steps.collect_summary.outputs.otobo_elasticsearch_rel_10_0_23 }}
      #otobo_elasticsearch_rel_10_0_24: ${{ steps.collect_summary.outputs.otobo_elasticsearch_rel_10_0_24 }}
      #otobo_elasticsearch_rel_10_0_25: ${{ steps.collect_summary.outputs.otobo_elasticsearch_rel_10_0_25 }}
      #otobo_elasticsearch_latest_10_0: ${{ steps.collect_summary.outputs.otobo_elasticsearch_latest_10_0 }}

      #otobo_elasticsearch_rel_10_1_12: ${{ steps.collect_summary.outputs.otobo_elasticsearch_rel_10_1_12 }}
      #otobo_elasticsearch_rel_10_1_13: ${{ steps.collect_summary.outputs.otobo_elasticsearch_rel_10_1_13 }}
      #otobo_elasticsearch_rel_10_1_14: ${{ steps.collect_summary.outputs.otobo_elasticsearch_rel_10_1_14 }}
      #otobo_elasticsearch_latest_10_1: ${{ steps.collect_summary.outputs.otobo_elasticsearch_latest_10_1 }}

      #otobo_elasticsearch_rel_11_0_8: ${{ steps.collect_summary.outputs.otobo_elasticsearch_rel_11_0_8 }}
      #otobo_elasticsearch_rel_11_0_9: ${{ steps.collect_summary.outputs.otobo_elasticsearch_rel_11_0_9 }}
      #otobo_elasticsearch_rel_11_0_10: ${{ steps.collect_summary.outputs.otobo_elasticsearch_rel_11_0_10 }}
      #otobo_elasticsearch_latest_11_0: ${{ steps.collect_summary.outputs.otobo_elasticsearch_latest_11_0 }}

      otobonginx_webproxy_rel_10_0_23: ${{ steps.collect_summary.outputs.otobonginx_webproxy_rel_10_0_23 }}
      otobonginx_webproxy_rel_10_0_24: ${{ steps.collect_summary.outputs.otobonginx_webproxy_rel_10_0_24 }}
      otobonginx_webproxy_rel_10_0_25: ${{ steps.collect_summary.outputs.otobonginx_webproxy_rel_10_0_25 }}
      otobonginx_webproxy_latest_10_0: ${{ steps.collect_summary.outputs.otobonginx_webproxy_latest_10_0 }}

      otobonginx_webproxy_rel_10_1_12: ${{ steps.collect_summary.outputs.otobonginx_webproxy_rel_10_1_12 }}
      otobonginx_webproxy_rel_10_1_13: ${{ steps.collect_summary.outputs.otobonginx_webproxy_rel_10_1_13 }}
      otobonginx_webproxy_rel_10_1_14: ${{ steps.collect_summary.outputs.otobonginx_webproxy_rel_10_1_14 }}
      otobonginx_webproxy_latest_10_1: ${{ steps.collect_summary.outputs.otobonginx_webproxy_latest_10_1 }}

      otobonginx_webproxy_rel_11_0_8: ${{ steps.collect_summary.outputs.otobonginx_webproxy_rel_11_0_8 }}
      otobonginx_webproxy_rel_11_0_9: ${{ steps.collect_summary.outputs.otobonginx_webproxy_rel_11_0_9 }}
      otobonginx_webproxy_rel_11_0_10: ${{ steps.collect_summary.outputs.otobonginx_webproxy_rel_11_0_10 }}
      otobonginx_webproxy_latest_11_0: ${{ steps.collect_summary.outputs.otobonginx_webproxy_latest_11_0 }}

      otobo_nninx_kerberos_webproxy_rel_10_0_23: ${{ steps.collect_summary.outputs.otobo_nninx_kerberos_webproxy_rel_10_0_23 }}
      otobo_nninx_kerberos_webproxy_rel_10_0_24: ${{ steps.collect_summary.outputs.otobo_nninx_kerberos_webproxy_rel_10_0_24 }}
      otobo_nninx_kerberos_webproxy_rel_10_0_25: ${{ steps.collect_summary.outputs.otobo_nninx_kerberos_webproxy_rel_10_0_25 }}
      otobo_nninx_kerberos_webproxy_latest_10_0: ${{ steps.collect_summary.outputs.otobo_nninx_kerberos_webproxy_latest_10_0 }}

      otobo_nninx_kerberos_webproxy_rel_10_1_12: ${{ steps.collect_summary.outputs.otobo_nninx_kerberos_webproxy_rel_10_1_12 }}
      otobo_nninx_kerberos_webproxy_rel_10_1_13: ${{ steps.collect_summary.outputs.otobo_nninx_kerberos_webproxy_rel_10_1_13 }}
      otobo_nninx_kerberos_webproxy_rel_10_1_14: ${{ steps.collect_summary.outputs.otobo_nninx_kerberos_webproxy_rel_10_1_14 }}
      otobo_nninx_kerberos_webproxy_latest_10_1: ${{ steps.collect_summary.outputs.otobo_nninx_kerberos_webproxy_latest_10_1 }}

      otobo_nninx_kerberos_webproxy_rel_11_0_8: ${{ steps.collect_summary.outputs.otobo_nninx_kerberos_webproxy_rel_11_0_8 }}
      otobo_nninx_kerberos_webproxy_rel_11_0_9: ${{ steps.collect_summary.outputs.otobo_nninx_kerberos_webproxy_rel_11_0_9 }}
      otobo_nninx_kerberos_webproxy_rel_11_0_10: ${{ steps.collect_summary.outputs.otobo_nninx_kerberos_webproxy_rel_11_0_10 }}
      otobo_nninx_kerberos_webproxy_latest_11_0: ${{ steps.collect_summary.outputs.otobo_nninx_kerberos_webproxy_latest_11_0 }}

      otobo_selenium_chrome_rel_10_0_23: ${{ steps.collect_summary.outputs.otobo_selenium_chrome_rel_10_0_23 }}
      otobo_selenium_chrome_rel_10_0_24: ${{ steps.collect_summary.outputs.otobo_selenium_chrome_rel_10_0_24 }}
      otobo_selenium_chrome_rel_10_0_25: ${{ steps.collect_summary.outputs.otobo_selenium_chrome_rel_10_0_25 }}
      otobo_selenium_chrome_latest_10_0: ${{ steps.collect_summary.outputs.otobo_selenium_chrome_latest_10_0 }}

      otobo_selenium_chrome_rel_10_1_12: ${{ steps.collect_summary.outputs.otobo_selenium_chrome_rel_10_1_12 }}
      otobo_selenium_chrome_rel_10_1_13: ${{ steps.collect_summary.outputs.otobo_selenium_chrome_rel_10_1_13 }}
      otobo_selenium_chrome_rel_10_1_14: ${{ steps.collect_summary.outputs.otobo_selenium_chrome_rel_10_1_14 }}
      otobo_selenium_chrome_latest_10_1: ${{ steps.collect_summary.outputs.otobo_selenium_chrome_latest_10_1 }}

      otobo_selenium_chrome_rel_11_0_8: ${{ steps.collect_summary.outputs.otobo_selenium_chrome_rel_11_0_8 }}
      otobo_selenium_chrome_rel_11_0_9: ${{ steps.collect_summary.outputs.otobo_selenium_chrome_rel_11_0_9 }}
      otobo_selenium_chrome_rel_11_0_10: ${{ steps.collect_summary.outputs.otobo_selenium_chrome_rel_11_0_10 }}
      otobo_selenium_chrome_latest_11_0: ${{ steps.collect_summary.outputs.otobo_selenium_chrome_latest_11_0 }}

    strategy:
      # create different images
      # note that there is no release build for the otobo-web-kerberos target
      # this currently has to be updated every release
      matrix:
        #target: [ 'otobo-web', 'otobo-elasticsearch', 'otobo-nginx-webproxy', 'otobo-nginx-kerberos-webproxy', 'otobo-selenium-chrome' ]
        target: [ 'otobo-web', 'otobo-nginx-webproxy', 'otobo-nginx-kerberos-webproxy', 'otobo-selenium-chrome' ]
        docker_tag: [
          'rel-10_0_23', 'rel-10_0_24', 'rel-10_0_25', 'latest-10_0',
          'rel-10_1_12', 'rel-10_1_13', 'rel-10_1_14', 'latest-10_1',
          'rel-11_0_8',  'rel-11_0_9',  'rel-11_0_10', 'latest-11_0'
        ]
        exclude:
          -
            target: 'otobo-selenium-chrome'
            docker_tag: 'rel-10_1_12'
          -
            target: 'otobo-nginx-kerberos-webproxy'
            docker_tag: 'rel-10_1_12'
          -
            target: 'otobo-nginx-webproxy'
            docker_tag: 'rel-10_1_12'
        include:
          # the latest release for every release branch - has to be updated
          -
            docker_tag: 'latest-10_0'
            patch:      'rel-10_0_25'
          -
            docker_tag: 'latest-10_1'
            patch:      'rel-10_1_14'
          -
            docker_tag: 'latest-11_0'
            patch:      'rel-11_0_10'

          # otobo-web uses different base images in the different release branches
          -
            target:     'otobo-web'
            docker_tag: 'rel-10_0_23'
            base_image: 'perl:5.32-buster'
          -
            target:     'otobo-web'
            docker_tag: 'rel-10_0_24'
            base_image: 'perl:5.32-buster'
          -
            target:     'otobo-web'
            docker_tag: 'rel-10_0_25'
            base_image: 'perl:5.32-buster'
          -
            target:     'otobo-web'
            docker_tag: 'latest-10_0'
            base_image: 'perl:5.32-buster'
          -
            target:     'otobo-web'
            docker_tag: 'rel-10_1_12'
            base_image: 'perl:5.36-bookworm'
          -
            target:     'otobo-web'
            docker_tag: 'rel-10_1_13'
            base_image: 'perl:5.36-bookworm'
          -
            target:     'otobo-web'
            docker_tag: 'rel-10_1_14'
            base_image: 'perl:5.36-bookworm'
          -
            target:     'otobo-web'
            docker_tag: 'latest-10_1'
            base_image: 'perl:5.36-bookworm'
          -
            target:     'otobo-web'
            docker_tag: 'rel-11_0_8'
            base_image: 'perl:5.38-bookworm'
          -
            target:     'otobo-web'
            docker_tag: 'rel-11_0_9'
            base_image: 'perl:5.38-bookworm'
          -
            target:     'otobo-web'
            docker_tag: 'rel-11_0_10'
            base_image: 'perl:5.38-bookworm'
          -
            target:     'otobo-web'
            docker_tag: 'latest-11_0'
            base_image: 'perl:5.38-bookworm'

          # otobo-nginx-kerberos-webproxy uses different dockerfiles in 10.0 and 10.1
          -
            target:     'otobo-nginx-kerberos-webproxy'
            docker_tag: 'rel-10_0_23'
            dockerfile: 'otobo.nginx-kerberos.dockerfile'
          -
            target:     'otobo-nginx-kerberos-webproxy'
            docker_tag: 'rel-10_0_24'
            dockerfile: 'otobo.nginx-kerberos.dockerfile'
          -
            target:     'otobo-nginx-kerberos-webproxy'
            docker_tag: 'rel-10_0_25'
            dockerfile: 'otobo.nginx-kerberos.dockerfile'
          -
            target:     'otobo-nginx-kerberos-webproxy'
            docker_tag: 'latest-10_0'
            dockerfile: 'otobo.nginx-kerberos.dockerfile'
          -
            target:     'otobo-nginx-kerberos-webproxy'
            docker_tag: 'rel-10_1_13'
            dockerfile: 'otobo.nginx-kerberos.dockerfile'
          -
            target:     'otobo-nginx-kerberos-webproxy'
            docker_tag: 'rel-10_1_14'
            dockerfile: 'otobo.nginx-kerberos.dockerfile'
          -
            target:     'otobo-nginx-kerberos-webproxy'
            docker_tag: 'latest-10_1'
            dockerfile: 'otobo.nginx-kerberos.dockerfile'

          # common info for every target; for nginx this includes the base imagie
          -
            target:     'otobo-web'
            dockerfile: 'otobo.web.dockerfile'
            context:    '.'
            repository: 'rotheross/otobo'
          #-
          #  target:     'otobo-elasticsearch'
          #  dockerfile: 'otobo.elasticsearch.dockerfile'
          #  context:    'scripts/elasticsearch'
          #  repository: 'rotheross/otobo-elasticsearch'
          #  base_image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.27'
          -
            target:     'otobo-nginx-webproxy'
            dockerfile: 'otobo.nginx.dockerfile'
            context:    'scripts/nginx'
            repository: 'rotheross/otobo-nginx-webproxy'
            base_image: 'nginx:mainline'
          -
            target:     'otobo-nginx-kerberos-webproxy'
            dockerfile: 'otobo.nginx.dockerfile'
            context:    'scripts/nginx'
            repository: 'rotheross/otobo-nginx-kerberos-webproxy'
            base_image: 'nginx:mainline'
          -
            target:     'otobo-selenium-chrome'
            dockerfile: 'otobo.selenium-chrome.dockerfile'
            context:    'scripts/test/sample'
            repository: 'rotheross/otobo-selenium-chrome'
            base_image: 'selenium/standalone-chrome-debug:3.141.59-20210422'
          -
            docker_tag: 'rel-11_0_8'
            fix_cldr:   1

    steps:

      -
        # These variables can be accessed in the env context
        name: Setting up the environment file (rel)
        if:   ${{ startsWith(matrix.docker_tag, 'rel') }}
        run: |
          patch=${{ matrix.docker_tag }}
          docker_tag=${{ matrix.docker_tag }}
          build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          (
            echo "otobo_branch=${patch}"
            echo "otobo_docker_tag=${docker_tag}"
            echo "otobo_ref=${{ matrix.repository }}:${docker_tag}"
            echo "otobo_base_image=${{ matrix.base_image }}"
            echo "otobo_build_date=${build_date}"
          ) >> $GITHUB_ENV

      -
        # These variables can be accessed in the env context
        name: Setting up the environment file (latest)
        if:   ${{ startsWith(matrix.docker_tag, 'latest') }}
        run: |
          patch=${{ matrix.patch }}
          docker_tag=${{ matrix.docker_tag }}
          build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          (
            echo "otobo_branch=${patch}"
            echo "otobo_docker_tag=${docker_tag}"
            echo "otobo_ref=${{ matrix.repository }}:${docker_tag}"
            echo "otobo_base_image=${{ matrix.base_image }}"
            echo "otobo_build_date=${build_date}"
          ) >> $GITHUB_ENV

      -
        # this step sets ${{ steps.check.outputs.needs-updating }}
        name: Check whether the base image was updated
        id: check
        uses: lucacome/docker-image-update-checker@v2
        with:
          base-image: ${{ env.otobo_base_image }}
          image:      ${{ env.otobo_ref }}

      -
        # print the result in any case
        name: Report the check result
        id: collect_summary
        run: |
          output_key=${{ matrix.target }}_${{ matrix.docker_tag }}
          cleaned_output_key=$(echo $output_key | tr - _)
          echo "$cleaned_output_key=${{ steps.check.outputs.needs-updating }}" >> $GITHUB_OUTPUT

      -
        # login to Docker Hub before the composite action
        # this avoids that secrets have to be passed
        name: Login to Docker Hub
        if: ${{ steps.check.outputs.needs-updating == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: 'check out so that the composite action becomes available'
        if: ${{ steps.check.outputs.needs-updating == 'true' }}
        uses: actions/checkout@v4

      -
        # the name of the Dockerfile might depend on the branch
        # there is a special case for rel-10_0 and rel-10_1
        name: Get the name of the Dockerfile
        if: ${{ steps.check.outputs.needs-updating == 'true' }}
        id: get-dockerfile
        run: |
          echo "dockerfile=${{ (matrix.target == 'otobo-nginx-kerberos-webproxy' && (startsWith(matrix.docker_tag, 'rel-10') || startsWith(matrix.docker_tag, 'latest-10'))) && 'otobo.nginx-kerberos.dockerfile' || matrix.dockerfile  }}" >> $GITHUB_OUTPUT

      -
        # Use a local composite action.
        # The action uses the inputs and the env context.
        name: 'Run local composite action'
        if: ${{ steps.check.outputs.needs-updating == 'true' }}
        uses: ./.github/actions/docker_image_update
        with:
          fix_cldr: ${{ matrix.fix_cldr }}
          dockerfile: ${{ steps.get-dockerfile.outputs.dockerfile }}
          context: ${{ matrix.context }}
          target: ${{ matrix.target }}
          dockerhub_tags: "${{ matrix.repository }}:${{ matrix.docker_tag }}"

      - name: 'check out so that the composite action becomes available'
        if: ${{ steps.check.outputs.needs-updating == 'true' }}
        uses: actions/checkout@v4

  # Write Summary
  WriteSummary:
    needs: CheckDockerImageUpdate
    runs-on: 'ubuntu-latest'
    steps:
      -
        name: Write a summary
        id: write_summary
        run: |
          cat <<END_JSON >> $GITHUB_STEP_SUMMARY
          ${{ toJSON(needs.CheckDockerImageUpdate.outputs) }}
          END_JSON
