# adapted from https://raku-advent.blog/2019/12/06/put-some-github-actions-in-your-raku-repositories/
name: 'prove scripts/test/Compile.t'
on: ['pull_request']
jobs:
    syntax_check:
        runs-on: 'ubuntu-latest'
        steps:
            - id: files
              uses: jitterbit/get-changed-files@v1

            - name: 'install dependencies'
              run: sudo apt install -y libxml2-utils libxml-libxslt-perl cpanminus

            - name: 'checkout otobo'
              uses: actions/checkout@v2

            # some diagnostics
            - name: perl -V
              run: perl -V
            - name: env
              run: env | sort

            # the setup is just like otobo.web.dockerfile and .dockerignore
            - name: set up Kernel/Config.pm
              run: 'cp --no-clobber Kernel/Config.pm.docker.dist Kernel/Config.pm'
            - name: fix Kernel/Config/Defaults.pm
              run: "perl -pi -e 's/^use lib /# disabled by syntax_check.yml: use lib/' Kernel/Config/Defaults.pm"
            - name: Remove Apache scripts and modules
              run: >
                rm -r
                scripts/apache*
                bin/cgi-bin
                Kernel/cpan-lib/Apache2
                Kernel/System/SupportDataCollector/Plugin/Webserver/Apache

            # The actual test step.
            # xargs adds the changed files to the prove command
            # :: tells prove that whatever follows should be passed to the test script
            - name: prove
              run: prove -I . -I Kernel/cpan-lib -I Custom --verbose scripts/test/Compile.t :: ${{ steps.files.outputs.added_modified }}
